services:
  backend:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      NODE_ENV: production
      REDIS: redis://host.docker.internal:6380
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /tmp:/tmp
      - /home/slawa/dev/flutter_site_container:/home/slawa/dev/flutter_site_container

  builder:
    restart: always
    build:
        context: .
        dockerfile: Dockerfile.builder
    depends_on:
      - redis
    env_file:
      - .env
    environment:
        NODE_ENV: production
        REDIS: redis://host.docker.internal:6380
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /tmp:/tmp
      - /home/slawa/dev/flutter_site_container:/home/slawa/dev/flutter_site_container

  redis:
    image: redis
    ports:
      - "6380:6379"

#  splunk:
#    image: splunk/splunk
#    ports:
#      - "8001:8000"
#      - "8088:8088"
#    environment:
#      - "SPLUNK_START_ARGS=--accept-license"
#      - "SPLUNK_PASSWORD=adminadmin"
