import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Providers } from "@/app/providers";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="min-h-full"
      style={{ background: "#161618", color: "rgba(255, 255, 245, .86)" }}
    >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-full p-0 m-0 dark`}
      >
        <Providers>
          <section className="flex flex-row gap-3 mx-auto p-0 min-h-full">
            <aside className="w-1/6 ms-48">Menu</aside>
            <div
              className="w-5/6 flex flex-col min-h-full"
              style={{ background: "#1e1e20" }}
            >
              <header className="border-b border-black p-5 pe-48">
                <h1 className="text-2xl">
                  <Link href="/">Web2App</Link>
                </h1>
              </header>
              <main className="flex-grow p-5 pe-48">{children}</main>
            </div>
          </section>
        </Providers>
      </body>
    </html>
  );
}
